function [fitresult, gof] = fit_titration(d_bound1, d_active1)
%CREATEFIT(D_BOUND1,D_ACTIVE1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : d_bound1
%      Y Output: d_active1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Aug-2015 21:23:12


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( d_bound1, d_active1 );

% Set up fittype and options.
ft = fittype( 'poly4' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'd_active1 vs. d_bound1', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel d_bound1
ylabel d_active1
grid on
p = [fitresult.p1 fitresult.p2 fitresult.p3 fitresult.p4 (fitresult.p5 - 0.5)];
roots(p)


